export const ADD_CONTACT_REQUEST = "ADD_CONTACT_REQUEST"
export const ADD_CONTACT_SUCCESS = "ADD_CONTACT_SUCCESS"
export const ADD_CONTACT_FAILURE = "ADD_CONTACT_FAILURE"


export const FETCH_CONTACT_REQUEST = "FETCH_CONTACT_REQUEST"
export const FETCH_CONTACT_SUCCESS = "FETCH_CONTACT_SUCCESS"
export const FETCH_CONTACT_FAILURE = "FETCH_CONTACT_FAILURE"

export const DELETE_CONTACT_REQUEST = "DELETE_CONTACT_REQUEST"
export const DELETE_CONTACT_SUCCESS = "DELETE_CONTACT_SUCCESS"
export const DELETE_CONTACT_FAILURE = "DELETE_CONTACT_FAILURE"

export const UPDATE_CONTACT_REQUEST = "UPDATE_CONTACT_REQUEST"
export const UPDATE_CONTACT_SUCCESS = "UPDATE_CONTACT_SUCCESS"
export const UPDATE_CONTACT_FAILURE = "UPDATE_CONTACT_FAILURE"